### ISSUE TITLE
Bug PlaceholderAPI

### ISSUE THREAD

**Issue by Golvore** [lucko/LuckPermsPlaceholders#6]
%luckperms_prefix_element_<element>% don't works help pls

**Comment by Andre601** [comment]
1. This is not the place for LuckPerms-related questions. Use the [Issue-tracker of LuckPerms](https://github.com/lucko/LuckPerms/issues) next time.
2. Check the [wiki of LuckPerms](https://github.com/lucko/LuckPerms/wiki/Placeholders#luckperms_prefix_element_element) the next time.

**Comment by BrainStone** [comment]
It’s a bug related to the placeholders, so it’s the right place.

**Comment by lucko** [comment]
It works fine, you just need to make sure you're using the latest version of the expansion

https://ci.lucko.me/job/LuckPermsPlaceholders/
