### ISSUE TITLE
LuckPerms PlaceHolder error

### ISSUE THREAD

**Issue by xGlenor** [lucko/LuckPermsPlaceholders#9]
Hey 😄 I have a problem with variables
i have a rank vip+8 and plugin FeatherBoard, LuckPermsMVdWHook
The problem is that the variable does not work because of the character "+"
variables: {luckperms_group_expiry_time_vip+8}

Could this be corrected?

**Comment by lucko** [comment]
This is an issue with MVdW placeholders, not LP.
